# Generated by Django 6.0.2 on 2026-02-24 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransitionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transition_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statetransitionlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='type',
            index=models.Index(fields=['scope'], name='common_type_scope_921768_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='uniq_workflow_stage_scope'),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='common.workflowstage'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='common.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='common.workflowstate'),
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['content_type', 'object_id'], name='state_log_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['created_at'], name='state_log_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='uniq_workflow_state_scope'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_workflow_transition_code'),
        ),
    ]
