# Generated by Django 6.0.2 on 2026-02-24 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='document_do_user_id_57c4b4_idx'),
        ),
    ]
